//
//  QuizBrain.swift
//  drinkinggame
//
//  Created by mladen on 31.3.21..
//

import Foundation
import CoreData
import UIKit


var ime : String = "Mladen"

struct QuizBrain {
    var brojPitanja = 0
    let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
    
    
    var imenaNiz = [Igrac]()
    
    mutating func vratiTekstPitanja() -> String{
        return pitanjaNiz[brojPitanja].tekst
    }
    
    func vratiIme() -> String{
        let broj = Int.random(in: 0..<imenaNiz.count)
        return imenaNiz[broj].ime ?? ""
    }
    
    
    mutating func procitajImena(){
        let request : NSFetchRequest<Igrac> = Igrac.fetchRequest()
        do{
            imenaNiz = try context.fetch(request)
        }catch{
            print("Error kod citanja imena")
        }
       
    }
    
    mutating func vratiRandomBroj() -> Int{
        return Int.random(in: 0...pitanjaNiz.count)
    }
    
    lazy var velicinaNizaPitanja = pitanjaNiz.count
    
    // MARK pitanja
    lazy var pitanjaNiz = [
        Pitanje(p: "Svi po jednu rakiju a ko nece 3 gutljaja pica po izboru"),
        Pitanje(p: "\(vratiIme()) uradi 5 sklekova ili 5 gutljaja"),
        Pitanje(p: "\(vratiIme()) koji je glavni grad Mongolije? Ako pogodis dajes 2 a promasis pijes 2"),
        Pitanje(p: "\(vratiIme()) pijes onoliko koliko si danas puta vrsio/la veliku nuzdu"),
        Pitanje(p: "Najveci alkoholicar daje 2 gutljaja. Bravo!"),
        Pitanje(p: "\(vratiIme()) ispricaj nam najludje mesto gde si vrsio/la malu nuzdu ili pij 4 gutljaja"),
        Pitanje(p:"\(vratiIme()) priznajte najgore mesto gde ste povratili i daj 2g"),
        Pitanje(p:"Zauzeti piju 2 g"),
        Pitanje(p:"Single daju 1g"),
        Pitanje(p:"\(vratiIme()) ako si los u kosarci pijes 1"),
        Pitanje(p:"Ko ima tik tok pije 3."),
        Pitanje(p:"Ko nema tik tok daje 1. Tako je"),
        Pitanje(p:"Ko nosi crne gace pije 1"),
        Pitanje(p:"Ko nosi crne carape daje 1 gutljaj"),
        Pitanje(p:"Ko ima android pije 2"),
        Pitanje(p:"Ko ima iphone pije 2"),
        Pitanje(p:"Ko ima najskuplji telefon daje 2. Burz"),
        Pitanje(p:"\(vratiIme()) pijes onoliko puta kolko si kostiju slomio/la"),
        Pitanje(p:"Svi koji nose naocare daju 1"),
        Pitanje(p:"\(vratiIme()) spank \(vratiIme()). Ako ta osoba odbije pije 3"),
        Pitanje(p:"\(vratiIme()) reci nam pickup line ili pij 2"),
        Pitanje(p:"Ko moze da pipne nos jezikom daje 1"),
        Pitanje(p:"\(vratiIme()) ako ne mozes da pipnes prste na nogama pijes 1 u suprotnom dajes 1"),
        Pitanje(p:"\(vratiIme()) uradi spagu. Ako mozes dajes 2 u suprotnom pijes 2"),
        Pitanje(p:"\(vratiIme()) uradi zvezdu. Ako uspes dajes 1 u suprotnom pijes 1"),
        Pitanje(p:"Ko vozi daje 1 gutljaj"),
        Pitanje(p:"\(vratiIme()) ako znas da vozis dajes 1 gutljaj. Ako ne znas pijes 1"),
        Pitanje(p:"Ko ne voli kokakolu pije 1"),
        Pitanje(p:"\(vratiIme()) ako volis knjige dajes 2 u suprotnom pijes 1"),
        Pitanje(p:"Ko ne voli da gleda horore pije 1"),
        Pitanje(p:"Studenti medicine piju 2"),
        Pitanje(p:"Ko je bio zaposlen nekad pije 1"),
        Pitanje(p:"\(vratiIme()) navedi jednog modnog dizajnera ili pij 2"),
        Pitanje(p:"\(vratiIme()) navedi trenera fudbalske reprezentacije ili pij 1"),
        Pitanje(p:"\(vratiIme()) ko je osvojio zlato na sv prvenstvu u fudbalu 2019. Tacan odg dajes 1, netacan pijes 1"),
        Pitanje(p:"\(vratiIme()) gde se nalazi Tibet? Ako ne znas pijes 2 u suprotnom dajes 1"),
        Pitanje(p:"\(vratiIme()) ako ne znas adresu \(vratiIme()) pijes 2"),
        Pitanje(p:"\(vratiIme()) kako se zove \(vratiIme()) majka. Znas dajes 2 ne znas pijes 2"),
        Pitanje(p:"Svi piju onoliko koliko kucnih ljubimaca imate"),
        Pitanje(p:"Ko je imao koronu pije 1"),
        Pitanje(p:"\(vratiIme()) ako znas sta je silos dajes 1. Ne znas pijes 2"),
        Pitanje(p:"\(vratiIme()) ko je olivera jevtic? Ako ne znas pijes 3"),
        Pitanje(p:"Najveca tracara pije 3. Shame"),
        Pitanje(p:"Najsmesnija osoba daje 2"),
        Pitanje(p:"\(vratiIme()) ako ste se kupali u moru goli dajete 2"),
        Pitanje(p:"\(vratiIme()) ako ste se nekad upisali od smeha pijete 1"),
        Pitanje(p:"\(vratiIme()) ako si izgubio tudju stvar nekad pijes 2"),
        Pitanje(p:"Ako ste polomili nekome telefon pijete 2"),
        Pitanje(p:"Ako ste bili u sudaru dajete 1"),
        Pitanje(p:"\(vratiIme()) zavrsi pesmu ili pijes 3. Dobro jutro nikome ____"),
        Pitanje(p:"\(vratiIme()) zavrsi recenicu iz Hamleta “biti ____”"),
        Pitanje(p:"\(vratiIme()) kako se zove kraljica engleske? Pogodis dajes 1, u suprotnom pijes 3"),
        Pitanje(p:"\(vratiIme()) od cega se pravi humus? Ne znas pijes 2"),
        Pitanje(p:"Ako ste povratili u klubu pijete 2 da ponovite"),
        Pitanje(p:"\(vratiIme()) ako si nekada nosio/la tange dajes 2"),
        Pitanje(p:"\(vratiIme()) navedi svoj najveci fetis ili pij 3"),
        Pitanje(p:"Kovrdzava kosa pije 2"),
        Pitanje(p:"Plavi ljudi daju 1"),
        Pitanje(p:"Zelene oci piju 1"),
        Pitanje(p:"Braon oci piju 2"),
        Pitanje(p:"Najvisi daje 2"),
        Pitanje(p:"\(vratiIme()) ako si najbolji prijatelj sa \(vratiIme()) pijete po 2"),
        Pitanje(p:"Ko nosi adidas patike pije 2"),
        Pitanje(p:"Ako koristite snapchat pijete 1"),
        Pitanje(p:"Osoba sa najvise pratilaca na ig daje 1"),
        Pitanje(p:"\(vratiIme()) pokazi nam gacice ili pij 2"),
        Pitanje(p:"\(vratiIme()) zagrli \(vratiIme()) ili pij 2"),
        Pitanje(p:"Ko veruje u boga pije 1"),
        Pitanje(p:"\(vratiIme()) ako si danas kupio/la nesto pijes 1"),
        Pitanje(p:"\(vratiIme()) pokazi nam brus ili pij 2"),
        Pitanje(p:"\(vratiIme()) pokazi nam pazuh ili pij 2"),
        Pitanje(p:"Ko nosi fiksnu protezu pije 1"),
        Pitanje(p:"\(vratiIme()) ako znas da kuvas dajes 2"),
        Pitanje(p:"Ko ne voli piletinu pije 2"),
        Pitanje(p:"\(vratiIme()) gde se nalazi tajna vecera"),
        Pitanje(p:"\(vratiIme()) koliko ima isusovih apostola"),
        Pitanje(p:"\(vratiIme()) ako si video/la \(vratiIme()) golog/golu dajes 2"),
        Pitanje(p:"\(vratiIme()) ako si spavao/la sa nekim ko takodje igra pijete 2"),
        Pitanje(p:"\(vratiIme()) ako volis boraniju dajes 1. Ako ne, pijes 2"),
        Pitanje(p:"\(vratiIme()) ako si nekad bio/la na koncertu dajes 1"),
        Pitanje(p:"\(vratiIme()) ako u leto nosis japanke pijes 1. Ako ne, dajes 1"),
        Pitanje(p:"\(vratiIme()) ako si bio nekad u Hrvatskoj pijes 2"),
        Pitanje(p:"\(vratiIme()) u kom veku je ziveo Sekspir? Znas dajes 2, ne znas pijes 1"),
        Pitanje(p:"\(vratiIme()) kako se Pikaso zove? Znas dajes 1, ne znas pijes 1."),
        Pitanje(p:"\(vratiIme()) kom drzavom je vladao Napoleon? Znas dajes 1, ne znas pijes 1."),
        Pitanje(p:"\(vratiIme()) koga bi poveo na pusto ostrvo? Pijete 2 zajedno"),
        Pitanje(p:"Ako ste se potukli sa nekim prisutnim pijete 1"),
        Pitanje(p:"\(vratiIme()) dozvoli \(vratiIme()) da te uhvati za grudi ili pij 2"),
        Pitanje(p:"\(vratiIme()) dozvoli \(vratiIme()) da te uhvati za polni organ ili pij 3"),
        Pitanje(p:"\(vratiIme()) ako imas kod sebe licnu kartu pijes 1"),
        Pitanje(p:"\(vratiIme()) ako su ti pare u dzepu pijes 2"),
        Pitanje(p:"\(vratiIme()) ako su ti pare u maski od telefona pijes 3. Uzas"),
        Pitanje(p:"Svi koji piju votku 1 gutljaj"),
        Pitanje(p:"Svi koji piju pivo 2 gutljaja"),
        Pitanje(p:"Ako ste se nekad maskirali za noc vestica pijete 1"),
        Pitanje(p:"Ako ste nekad leteli avionom pijete 1"),
        Pitanje(p:"Ako ste bili na drugom kontinentu dajete 1"),
        Pitanje(p:"Ako ste igrali among us pijete 1"),
        Pitanje(p:"\(vratiIme()) ako si slao/la gole slike dajes 2"),
        Pitanje(p:"\(vratiIme()) ako si imao/la decka u drugom gradu dajes 1"),
        Pitanje(p:"Ako ste bili u ribolovcu na 18 rodjendanu pijete 1"),
        Pitanje(p:"\(vratiIme()) sada si \(vratiIme()) ljubimac. Neka ti ta osoba veze povodac oko vrata i vodi te po sobi. Ako odbijes pijes 3"),
        Pitanje(p:"\(vratiIme()) uzmi dim cigare ili pij 1 gutljaj"),
        Pitanje(p:"Zavrsi tekst “hey there Dilalah____” ili pij 1"),
        Pitanje(p:"\(vratiIme()) ko peva pesmu bebe bebe? Pij 2 ako ne znas"),
        Pitanje(p:"\(vratiIme()) zavrsi pesmu “na zlatnom stolu ispred mene____”"),
        Pitanje(p:"\(vratiIme()) zavrsi pesmu “ i kako ti se cini kada_____”"),
        Pitanje(p:"\(vratiIme()) zavrsi “i ja uze ovako ______”"),
        Pitanje(p:"\(vratiIme()) ko glumi Terminatora? Ako ne znas pij 2"),
        Pitanje(p:"\(vratiIme()) ko je bio zarobljen u lavirintu u antickoj grckoj? Ako ne znas pij 2. Ako znas dajes 2"),
        Pitanje(p:"\(vratiIme()) koja je planeta najbliza suncu? 2"),
        Pitanje(p:"\(vratiIme()) ako citas ispovesti pij 1"),
        Pitanje(p:"Ko nema facebook daje 1"),
        Pitanje(p:"\(vratiIme()) ako si nekad nosio/la dopicnjak dajes 2. Bravo"),
        Pitanje(p: "Ko je nosio mider daje 2. Zao nam je"),
        Pitanje(p:"\(vratiIme()) ako si nekad pao/la u stiklama dajes 2"),
        Pitanje(p:"\(vratiIme()) ako si se nekad posvadjao/la u gradskom prevozu pijes 1"),
        Pitanje(p:"\(vratiIme()) ako si nekad ukrao/la od roditelja pare pijes 1"),
        Pitanje(p:"\(vratiIme()) ako si probao drogu pijes 2. Sramotno"),
        Pitanje(p:"\(vratiIme()) ako si danas gledao/la pornice dajes 1"),
        Pitanje(p:"Ko trenutno jede pije 2. Krmaco"),
        Pitanje(p:"\(vratiIme()) ako spavas sa plisanim igrackama dajes 1. Cute"),
        Pitanje(p:"\(vratiIme()) ako spavas sa > 1 jastukom pijes 1"),
        Pitanje(p:"\(vratiIme()) pijes koliko imas brace i sestara"),
        Pitanje(p:"Piju svi koji zive u zgradi po 1"),
        Pitanje(p:"Svi koji zive u kuci piju po 1"),
        Pitanje(p:"\(vratiIme()) ako si nekad imao/la kaktus pijes 1"),
        Pitanje(p:"\(vratiIme()) sta kazes kad te jebu?"),
        Pitanje(p:"Ko je jedinica pije 1"),
        Pitanje(p:"\(vratiIme()) ako si povratio/la u taksiju pijes 2"),
        Pitanje(p:"\(vratiIme()) ako si imao/la grupni seks dajes 2"),
        Pitanje(p:"\(vratiIme()) ako si duvao/la pijes 1"),
        Pitanje(p:"\(vratiIme()) navedi jednu pesmu Selene Gomez ili pij 1"),
        Pitanje(p:"\(vratiIme()) navedi 1 pesmu lady gage ili pij 1"),
        Pitanje(p:"\(vratiIme()) navedi jednu pesmu sabana saulica ili pij 2"),
        Pitanje(p:"\(vratiIme()) navedi jednu pesmu marije serifovic ili pij 1"),
        Pitanje(p:"\(vratiIme()) ako znas sta je skracenica HoReCa dajes 2. U suprotnom pijes 2"),
        Pitanje(p:"\(vratiIme()) navedi jednu pesmu BTS ili pij 1"),
        Pitanje(p:"\(vratiIme()) ako pogodis \(vratiIme()) omiljeni slatkis dajes 1. U suprotnom pijes 1"),
        Pitanje(p:"\(vratiIme()) navedi naziv jedne piramide u Egiptu i daj 1 gutljaj ili pij 2"),
        Pitanje(p:"\(vratiIme()) ako si nekad bio/la na brodu daj 1 gutljaj"),
        Pitanje(p:"\(vratiIme()) popij 1 gutljaj sa \(vratiIme()) kao na svadbi"),
        Pitanje(p:"\(vratiIme()) ako si nekad bio prevaren/a dajes 1"),
        Pitanje(p:"\(vratiIme()) ako si nekad prevario/la pijes 2"),
        Pitanje(p:"Svi koji nose farmerke piju 1"),
        Pitanje(p:"Svi koji su u trenerci piju 1"),
        Pitanje(p:"\(vratiIme()) zovni majku i reci joj da je volis. Ako odbijes pij 2 u suprotnom daj 1"),
        Pitanje(p:"\(vratiIme()) ako umes da igras sah daj 1 gutljaj"),
        Pitanje(p:"\(vratiIme()) ako si osoba koja place kad se posvadja daj 1. U suprotnom pij 1"),
        Pitanje(p:"\(vratiIme()) stoj na jednoj nozi 10 minuta. Ako neces pij 3"),
        Pitanje(p:"\(vratiIme()) okreni svima ledja na 10 minuta. Ako odbijes pij 2"),
        Pitanje(p:"\(vratiIme()) idi u cosak na 10 minuta. Ako neces pij 2"),
        Pitanje(p:"\(vratiIme()) ako su te roditelji videli u pijanom stanju dajes 1"),
        Pitanje(p:"\(vratiIme()) ako si povratio/la negde u kuci a da to nije wc daj 2. Good job"),
        Pitanje(p:"\(vratiIme()) ako si povratio/la u krevet daj 1"),
        Pitanje(p:"\(vratiIme()) ako si povratio/la po zidu daj 1"),
        Pitanje(p:"\(vratiIme()) ako si povracao/la po sebi daj 1"),
        Pitanje(p:"Ako si nekad pijan upao u govna pij 2"),
        Pitanje(p:"Glasanje pocinje. Osoba koja se najvise razbijala na 18im rodjendanima daje 2 gutljaja. Svaka cast!"),
        Pitanje(p:"\(vratiIme()) opisi svoje prvo pijanstvo i daj 1 gutljaj"),
        Pitanje(p:"Ako je danas paran datum \(vratiIme()) pije ovoliko gutljaja —> poslednja cifra datuma / 2"),
        Pitanje(p:"Svi piju onoliko gutljaja koliko imaju samoglasnika u imenu"),
        Pitanje(p:"\(vratiIme()) pijes 2 ako si ikad bio/la izbacen/a sa proslave"),
        Pitanje(p:"Do kraja partije \(vratiIme()) i \(vratiIme()) piju zajedno. I jedno i drugo moraju piti onoliko koliko onaj drugi pije"),
        Pitanje(p:"\(vratiIme()) ako si plakao/la u poslednja 2 dana dajes 1"),
        Pitanje(p: "Nikad nisam. \(vratiIme())"),
        Pitanje(p:"\(vratiIme()) tverkuj ili pij 2"),
        Pitanje(p:"\(vratiIme()) pojedi parce papira ili pij 2"),
        Pitanje(p:"\(vratiIme()) pojedi maramicu ili pij 3"),
        Pitanje(p:"\(vratiIme()) do kraja partije ne smes da kazes rec “ja”"),
        Pitanje(p:"\(vratiIme()) dozvoli da te \(vratiIme()) \(vratiIme()) \(vratiIme()) udare po guzici ili pij 2"),
        Pitanje(p:"\(vratiIme()) zovni random broj i flertuj sa njima ili pij 2"),
        Pitanje(p:"\(vratiIme()) dozvoli svima da ti preturaju po torbi ili pij 1"),
        Pitanje(p:"\(vratiIme()) olizi kvaku ili pij 2"),
        Pitanje(p:"\(vratiIme()) olizi zid ili pij 1"),
        Pitanje(p:"\(vratiIme()) dozvoli da te \(vratiIme()) golica ili pij 1"),
        Pitanje(p:"\(vratiIme()) sedi u \(vratiIme()) krilu 5 minuta ili pij 2"),
        Pitanje(p:"\(vratiIme()) drzi ruku na unutrasnjosti butine osobe desno od tebe 2 minuta ili pij 1"),
        Pitanje(p:"\(vratiIme()) reci nam jednu stvar sto tvoji roditelji ne smeju saznati o tebi ili pij 2"),
        Pitanje(p:"\(vratiIme()) koji je najduzi period koliko se nisi tusirao/la. Taj broj / 2 i toliko pij"),
        Pitanje(p:"\(vratiIme()) sta je najveca laz sto si ikada rekao/la. Ako odbijes da kazes pij 2"),
        Pitanje(p:"\(vratiIme()) pretvaraj se da si \(vratiIme()) na 5 minuta ili pij 2"),
        Pitanje(p:"\(vratiIme()) izvedi striptiz ili pij 3"),
        Pitanje(p:"\(vratiIme()) pusti pesmu uz koju zelis da imas seks. Ako odbijes pij 1"),
        Pitanje(p:"\(vratiIme()) imitiraj \(vratiIme()) a ostali neka pogadjaju. Prvi koji pogodi daje 1 gutljaj"),
        Pitanje(p:"\(vratiIme()) oponasaj \(vratiIme()) narednih 5 minuta"),
        Pitanje(p:"\(vratiIme()) ako pogodis koliko je sati dajes 1. Pijes 1 u suprotnom"),
        Pitanje(p:"\(vratiIme()) sisaj palac 5 sekundi ili pij 1"),
        Pitanje(p:"\(vratiIme()) odaberi \(vratiIme()), \(vratiIme()), \(vratiIme()) za fuck marry kill"),
        Pitanje(p:"\(vratiIme()) reci \(vratiIme()) koja mu/joj je najruznija slika na ig ili pij 1"),
        Pitanje(p:"\(vratiIme()) reci \(vratiIme()) koja mu/joj je najlepsa slika na ig i pijte zajedno po 1"),
        Pitanje(p:"\(vratiIme()) uradi kolut unapred"),
        Pitanje(p:"\(vratiIme()) uradi kolut unazad"),
        Pitanje(p:"\(vratiIme()) pogodi prosek \(vratiIme()). Ako si u granicama +-0.3 dajes 1 gutljaj. U suprotnom pijes 1"),
        Pitanje(p:"\(vratiIme()) olizi \(vratiIme()) prst ili pij 1"),
        Pitanje(p:"\(vratiIme()) sipaj \(vratiIme()) nesto u pice ili ta osoba pije 2 gutljaja"),
        Pitanje(p:"\(vratiIme()) pij onoliko gutljaja koliko imas u drugoj cifri % baterije/2"),
        Pitanje(p:"\(vratiIme()) pij onoliko koji broj obuce nosis (druga cifra /3)"),
        Pitanje(p:"\(vratiIme()) ako pogodis koji telefon \(vratiIme()) ima dajes 1. U suprotnom pijes 1"),
        Pitanje(p:"\(vratiIme()) ako si bio/la u novom sadu pij 1. Ako nisi daj 1"),
        Pitanje(p:"\(vratiIme()) ako si bio/la u tc galerija daj 1. Pij 1 ako nisi"),
        Pitanje(p:"\(vratiIme()) ako si nekada uzeo/la ekser pij 2. Ako nisi daj 1"),
        Pitanje(p:"\(vratiIme()) ako si bio/la u pragu pij 1. Daj 1"),
        Pitanje(p:"\(vratiIme()) ako znas slepo kucanje daj 1. Pij 1 u suprotnom"),
        Pitanje(p:"\(vratiIme()) ako sada sedis u pogrbljenom polozaju pij 1. Daj 1"),
        Pitanje(p:"Pije 1 ko ima najduze nokte"),
        Pitanje(p:"Pije 1 ko ima najduzu kosu"),
        Pitanje(p:"Pije 2 ko ima najkracu kosu"),
        Pitanje(p:"\(vratiIme()) ako dobro igras fudbal daj 1. Pij 1 u suprotnom"),
        Pitanje(p:"\(vratiIme()) ako ne znas ko je nikolijina majka pij 1. U suprotnom daj 1"),
        Pitanje(p:"\(vratiIme()) ako znas koliko godina ima \(vratiIme()) otac daj 1. U suprotnom pijes 1"),
        Pitanje(p:"\(vratiIme()) ako si nekad probao/la apsent daj 1. Pij 1 u suprotnom"),
        Pitanje(p:"\(vratiIme()) sta jedu koale? Ako ne znas pij 1. Daj 1 u suprotnom"),
        Pitanje(p:"\(vratiIme()) ako si nekada probao/la tofu dajes 1. Pijes 1 u suprotnom"),
        Pitanje(p:"\(vratiIme()) ako znas kako se zovu Obamine cerke dajes 2"),
        Pitanje(p:"\(vratiIme()) ako si nekada video zmiju u prirodi dajes 1"),
        Pitanje(p:"\(vratiIme()) ako znas ime vucicevog sina dajes 2"),
        Pitanje(p:"\(vratiIme()) navedi jednu pesmu mimi mercedez ili pij 2"),
        Pitanje(p:"\(vratiIme()) navedi jednu pesmu beogradskog sindikata ili pij 1"),
        Pitanje(p:"\(vratiIme()) kako se zove osnovac Microsofta? Ako ne znas pijes 2"),
        Pitanje(p:"\(vratiIme()) ako znas ko peva slobodno me rani dajes 1"),
        Pitanje(p:"\(vratiIme()) ako si izgubio telefon nekad pijes 2"),
        Pitanje(p:"\(vratiIme()) ako si se napio/la na plocama nekad pijes 1"),
        Pitanje(p:"\(vratiIme()) ako si jako nestrpljiva osoba pij 1"),
        Pitanje(p:"\(vratiIme()) ako si jako glasna osoba pij 1"),
        Pitanje(p:"\(vratiIme()) ako si tiha osoba pij 1"),
        Pitanje(p:"\(vratiIme()) ako si uzeo/la 100€ od vucica dajes 1"),
        Pitanje(p:"\(vratiIme()) ako si igrao/la nekad beer pong dajes 1"),
        Pitanje(p:"\(vratiIme()) ako znas ko je milic vukasinovic dajes 1. Pijes 1 u suprotnom"),
        Pitanje(p:"\(vratiIme()) ako znas pravo ime zoi dajes 1"),
        Pitanje(p:"\(vratiIme()) sta kazes kad te jebu? Pij 1"),
        Pitanje(p:"\(vratiIme()) osoba koju znas najduze pije sa tobom po 1"),
        Pitanje(p:"\(vratiIme()) osoba koju znas najkrace pije sa tobom po 1"),
        Pitanje(p:"\(vratiIme()) osoba koja zna najvise tvojih tajni pije 1"),
        Pitanje(p:"\(vratiIme()) za svaku godinu koju si nosio/la protezu pij 1 gutljaj"),
        Pitanje(p:"\(vratiIme()) ako si nekad bio/la kod \(vratiIme()) u kuci dajes 1"),
        Pitanje(p:"\(vratiIme()) ako ne znas da zvizdis pij 1"),
        Pitanje(p:"\(vratiIme()) navedi 1 gastozovu pesmu ili pij 1"),
        Pitanje(p:"\(vratiIme()) ako znas kada je \(vratiIme()) rodjendan dajes 1"),
        Pitanje(p:"\(vratiIme()), \(vratiIme()), \(vratiIme()) poljubite se svi zajedno ili pijte svi po 1 (cak i ako samo 1 odustane)"),
        Pitanje(p:"\(vratiIme()) uradi most ili pij 1"),
        Pitanje(p:"Ko prvi uhvati \(vratiIme()) za sisu daje 3. Ako \(vratiIme()) odbije pije 1"),
        Pitanje(p:"\(vratiIme()) ako znas gde je rodjen Nikola Tesla dajes 2. U suprotnom pij 1"),
        Pitanje(p:"\(vratiIme()) ako nisi odgledao/la sve delove hari potera pijes 1. U suprotnom daj 1"),
        Pitanje(p:"Ko prvi uhvati \(vratiIme()) za dupe daje 2"),
        Pitanje(p:"\(vratiIme()) koja zivotinja se ne pominje u bibliji? Znas dajes 2, ne znas pijes 1"),
        Pitanje(p:"Ko prvi uhvati Ognjena za penis daje 3"),
        Pitanje(p:"\(vratiIme()) dajes onoliko gutljaja koliko si se puta danas samozadovoljavao/la. Ako je taj broj 0 pijes 1"),
        Pitanje(p:"\(vratiIme()) ne sme da pije narednih 10 minuta. Previse si pijan/a. Ako prekrsis pravilo pijes 3"),
        Pitanje(p:"\(vratiIme()) ispricaj nam najludje mesto gde si imao/la odnos i daj 3 ili pij 2"),
        Pitanje(p:"\(vratiIme()) poljubi \(vratiIme()) u stopala ili pij 2"),
        Pitanje(p:"\(vratiIme()) poljubi osobu koju smatras da je najseksi u prostoriji ili pij 2"),
        Pitanje(p:"\(vratiIme()) poljubi \(vratiIme()) ili pij onoliko koliko se ostali dogovore da ti daju"),
        Pitanje(p:"\(vratiIme()) plesi u krilu (lapdance) \(vratiIme()) ili pij 2"),
        Pitanje(p:"\(vratiIme()) pokazi nam svoju seksi guzu ili pij 2"),
        Pitanje(p:"\(vratiIme()) polizi se sa \(vratiIme()) ili pijte oboje po 2"),

    
    ]
}
